### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ShadicSlash** [onnowhere/youtube_music_playlist_downloader#10]
Downloading 'https://www.youtube.com/watch?v=NhZHiPNjuTA'... (1/32)
ERROR: unable to download video data: HTTP Error 403: Forbidden
Unable to download video: list index out of range

I didn't use it for a while and now I cannot download songs that are longer than 1:30 min.
I remade my cookie file just to make sure and still get the same errors.
Is it because the packages need updates inside the Windows app?

Thank you

**Comment by onnowhere** [comment]
Fixing this now, needed an update to yt-dlp

**Comment by ShadicSlash** [comment]
I'll be testing right when youre done

**Comment by onnowhere** [comment]
@ShadicSlash this is unrelated to the current issue, but would you be opposed to song lyrics being added to video metadata by default in the lyrics fields? I'm preparing this feature for the update. My thinking is to enable it by default along with the other metadata fields since it should not impact much including file size, and would come in use when the music playback program supports lyrics.

**Comment by ShadicSlash** [comment]
This can’t be a downside I suppose.

**Comment by onnowhere** [comment]
@ShadicSlash updated in https://github.com/onnowhere/youtube_music_playlist_downloader/releases/tag/1.3.0

**Comment by onnowhere** [comment]
Closed, assuming fixed
